openapi: 3.0.0
servers:
  - url: http://localhost:3000/
info:
  title: Compass Mart
  description: Compass Mart API
  version: 0.0.1
  contact:
    email: bruno.cirino.pb@compasso.com.br
  license:
    name: "Lincença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html
tags:
  - name: developers
    description: Operations available to regular developers
paths:
  /api/v1/product:
    get:
      summary: Search all products
      description: Search all products in system.
      tags:
        - developers
      parameters:
      - name: department
        in: query
        required: false
        schema:
          type: string
      - name: brand
        in: query
        required: false
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: integer
          minimum: 1
          format: int32
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          minimum: 1
          format: int32
      responses:
        200:
          description: search results matching criteria.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        404:
          description: Products not found, empty page.
        500:
          description: Error page.
    post:
      summary: Insert product in system
      description: Insert product in system.
      tags:
      - developers
      requestBody:
        content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: Azeites, Óleos e Vinagres
                  description:
                    type: string
                    example: Óleo de Soja Soya Garrafa 900ml
                  department:
                    type: string
                    example: Mercearia
                  brand:
                    type: string
                    example: Soya
                  price:
                    type: number
                    example: 9.49
                  qtd_stock:
                    type: number
                    example: 30137
                  stock_control_enabled:
                    type: boolean
                    example: true
                  bar_codes:
                    type: string
                    example: 7891107101621
      responses:
        201:
          description: success insert product in system.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        400:
          description: This bar_codes is already in use.
        500:
          description: Error page.
  /api/v1/product/low_stock:
    get:
      summary: Search low stock
      description: Search all products with low stock.
      tags:
        - developers
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          minimum: 1
          format: int32
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          minimum: 1
          format: int32
      responses:
        200:
          description: search results matching criteria.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        404:
          description: Products not found, empty page.
        500:
          description: Error page.
  /api/v1/product/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Search product by ID
      description: Search product by ID in system.
      tags:
        - developers
      responses:
          200:
            description: search results matching criteria.
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Product"
          404:
            description: Product not found, empty page.
          500:
            description: Error page.
    put:
      summary: Update product by ID
      description: Product update passing all data to the system.
      tags:
        - developers
      requestBody:
        content:
            application/json:
              schema:
                type: object
                required:
                - title
                - description
                - department
                - brand
                - price
                - qtd_stock
                - stock_control_enabled
                - bar_codes
                properties:
                  title:
                    type: string
                    example: Azeites, Óleos e Vinagres
                  description:
                    type: string
                    example: Óleo de Soja Soya Garrafa 900ml
                  department:
                    type: string
                    example: Mercearia
                  brand:
                    type: string
                    example: Soya
                  price:
                    type: number
                    example: 9.49
                  qtd_stock:
                    type: number
                    example: 30137
                  stock_control_enabled:
                    type: boolean
                    example: true
                  bar_codes:
                    type: string
                    example: 7891107101621
      responses:
        200:
          description: Product updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        404:
          description: Product not found, empty page.
        500:
          description: Error page.
    patch:
      summary: Update product by ID
      description: Product update can only pass one data.
      tags:
        - developers
      requestBody:
        content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: Azeites, Óleos e Vinagres
                  description:
                    type: string
                    example: Óleo de Soja Soya Garrafa 900ml
                  department:
                    type: string
                    example: Mercearia
                  brand:
                    type: string
                    example: Soya
                  price:
                    type: number
                    example: 9.49
                  qtd_stock:
                    type: number
                    example: 30137
                  stock_control_enabled:
                    type: boolean
                    example: true
                  bar_codes:
                    type: string
                    example: 7891107101621
      responses:
        200:
          description: Product updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        404:
          description: Product not found, empty page.
        500:
          description: Error page.
    delete:
      summary: Delete product by ID
      description: Delete product by ID in system.
      tags:
        - developers
      responses:
          204:
            description: Not content.
          404:
            description: Product not found, empty page.
          500:
            description: Error page.
  /api/v1/product/csv:
    post:
      summary: Insert product in system by csv file
      description: Insert product in system by csv file.
      tags:
      - developers
      requestBody:
        content:
          csv:
            schema:
              type: string
              format: binary
      responses:
        201:
          description: success insert product in system.
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: number
                    example: 200
                  errors:
                    type: number
                    example: 8
                  error_details:
                    type: array
                    items:
                      properties:
                        title:
                          type: string
                          example: Azeites, Óleos e Vinagres
                        bar_codes:
                          type: string
                          example: 7891107101621
                        error:
                          type: string
                          example: bar_codes duplicate
        400:
          description: This bar_codes is already in use.
        500:
          description: Error page.
components:
  schemas:
    Product:
      type: object
      required:
      - title
      - description
      - department
      - brand
      - price
      - qtd_stock
      - bar_codes
      properties:
        _id:
          type: string
          format: ObjectId
          example: 62e45ac8cd18211344d41a96
        title:
          type: string
          example: Azeites, Óleos e Vinagres
        description:
          type: string
          example: Óleo de Soja Soya Garrafa 900ml
        department:
          type: string
          example: Mercearia
        brand:
          type: string
          example: Soya
        price:
          type: number
          example: 9.49
        qtd_stock:
          type: number
          example: 30137
        stock_control_enabled:
          type: boolean
          example: true
        bar_codes:
          type: string
          example: 7891107101621
        created_at:
          type: string
          format: date-time
          example: '2021-06-30T20:18:23+00:00'
        update_at:
          type: string
          format: date-time
          example: '2021-06-30T20:18:23+00:00'